---
name: POE-Component-Data-SimplePassword
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: POE wrapper around Data::SimplePassword
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::SimplePassword: 0.04
  Math::Pari: 2.0108
  POE: 0.9999
  POE::Component::NonBlockingWrapper::Base: 0.002
build_requires:
  Test::More: 0
provides:
  POE::Component::Data::SimplePassword:
    file: lib/POE/Component/Data/SimplePassword.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
